table_data = [
   {
      "hqstate" : "Alabama",
      "focus" : "Rural",
      "blendedsubjects" : "Comprehensive",
      "hqcity" : "Montgomery",
      "gradesserved" : "8-12",
      "postdate" : "May 12, 2011",
      "blendedgrades" : "8-12",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-innosight/access-distance-learning-5/",
      "title" : "ACCESS Distance Learning",
      "type" : "State department of education",
      "hq" : "Montgomery, Alabama",
      "blendedenrollment" : "41,161 (2009-10 school year)"
   },
   {
      "hqstate" : "Texas",
      "focus" : "General",
      "blendedsubjects" : "Foreign language, math, reading, other",
      "detail" : " ",
      "hqcity" : "Austin",
      "gradesserved" : "1-5",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-innosight/acton-academy/",
      "postdate" : "May 12, 2011",
      "blendedgrades" : "1-5",
      "title" : "Acton Academy",
      "type" : "Independent school",
      "hq" : "Austin, Texas",
      "blendedenrollment" : "16"
   },
   {
      "hqstate" : "Virginia",
      "focus" : "Dropout prevention/recovery",
      "blendedsubjects" : "Comprehensive",
      "detail" : " ",
      "hqcity" : "Williamsburg",
      "gradesserved" : "9-12",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-innosight/advancepath-academics-inc/",
      "postdate" : "May 12, 2011",
      "blendedgrades" : "9-12",
      "title" : "AdvancePath Academics, Inc.",
      "type" : "Nonprofit or for-profit service provider",
      "hq" : "Williamsburg, Virginia",
      "blendedenrollment" : "4,000-4,5000 in 23 academies"
   },
   {
      "hqstate" : "California",
      "focus" : "Urban",
      "blendedsubjects" : "Core subjects",
      "detail" : "Pilot study, summer program",
      "hqcity" : "Los Angeles",
      "gradesserved" : "9-12",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-innosight/alliance-college-ready-public-schools/",
      "postdate" : "May 12, 2011",
      "blendedgrades" : "Pilot study: 9 Summer program: 9-12",
      "title" : "Alliance College-Ready Public Schools",
      "type" : "CMO",
      "hq" : "Los Angeles, California",
      "blendedenrollment" : "Unavailable"
   },
   {
      "hqstate" : "Colorado",
      "focus" : "Parochial",
      "blendedsubjects" : "Comprehensive",
      "detail" : "Simple School Design",
      "hqcity" : "Lone Tree",
      "gradesserved" : "1-8",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-usersubmissions/anastasis-academy/",
      "postdate" : "May 23, 2011",
      "blendedgrades" : "1-8",
      "title" : "Anastasis Academy",
      "type" : "Independent school",
      "hq" : "Lone Tree, Colorado",
      "blendedenrollment" : "60"
   },
   {
      "hqstate" : "Rhode Island",
      "focus" : "Urban",
      "detail" : " ",
      "hqcity" : "Providence",
      "gradesserved" : "9-12",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-innosight/big-picture-learning/",
      "postdate" : "May 12, 2011",
      "blendedgrades" : "9-12",
      "title" : "Big Picture Learning",
      "type" : "Nonprofit or for-profit service provider",
      "hq" : "Providence, Rhode Island",
      "blendedenrollment" : "9,000"
   },
   {
      "hqstate" : "New York",
      "focus" : "Urban",
      "blendedsubjects" : "Core subjects",
      "detail" : "In partnership with Diploma Plus",
      "hqcity" : "New York",
      "gradesserved" : "PreK-12",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-innosight/brownsville-academy-high-school/",
      "postdate" : "May 13, 2011",
      "blendedgrades" : "9-12",
      "title" : "Brownsville Academy High School",
      "type" : "District",
      "hq" : "New York, New York",
      "blendedenrollment" : "171"
   },
   {
      "hqstate" : "Pennsylvania",
      "focus" : "General",
      "blendedsubjects" : "Comprehensive",
      "detail" : " ",
      "hqcity" : "Enola",
      "gradesserved" : "K-12",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-innosight/capital-area-online-learning-association/",
      "postdate" : "May 13, 2011",
      "blendedgrades" : "6-12",
      "title" : "Capital Area Online Learning Association",
      "type" : "State intermediate unit",
      "hq" : "Enola, Pennsylvania",
      "blendedenrollment" : "1,224"
   },
   {
      "hqstate" : "Arizona",
      "focus" : "Urban",
      "blendedsubjects" : "Comprehensive",
      "detail" : " ",
      "hqcity" : "Yuma",
      "gradesserved" : "6-12",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-innosight/carpe-diem-collegiate-high-school-and-middle-school-cdchs/",
      "postdate" : "May 13, 2011",
      "blendedgrades" : "6-12",
      "title" : "Carpe Diem Collegiate High School and Middle School (CDCHS)",
      "type" : "CMO",
      "hq" : "Yuma, Arizona",
      "blendedenrollment" : "273"
   },
   {
      "hqstate" : "Illinois",
      "focus" : "Urban",
      "blendedsubjects" : "Core subjects",
      "detail" : " ",
      "hqcity" : "Chicago",
      "gradesserved" : "K-12",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-innosight/chicago-international-charter-school/",
      "postdate" : "May 13, 2011",
      "blendedgrades" : "6-12",
      "title" : "Chicago International Charter School",
      "type" : "CMO",
      "hq" : "Chicago, Illinois",
      "blendedenrollment" : "To be determined"
   },
   {
      "hqstate" : "Illinois",
      "focus" : "Urban",
      "blendedsubjects" : "Math, reading",
      "detail" : "Additional Learning Opportunities Initiative",
      "hqcity" : "Chicago",
      "gradesserved" : "PreK-12",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-innosight/chicago-public-schools/",
      "postdate" : "May 13, 2011",
      "blendedgrades" : "1-8",
      "title" : "Chicago Public Schools",
      "type" : "District",
      "hq" : "Chicago, Illinois",
      "blendedenrollment" : "6,000 (in first 15-school pilot)"
   },
   {
      "hqstate" : "New York",
      "focus" : "Urban",
      "blendedsubjects" : "Comprehensive",
      "detail" : " ",
      "hqcity" : "New York",
      "gradesserved" : "9-12",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-innosight/city-prep-academies/",
      "postdate" : "May 13, 2011",
      "blendedgrades" : "9-12",
      "title" : "City Prep Academies",
      "type" : "CMO",
      "hq" : "New York, New York",
      "blendedenrollment" : "To be determined"
   },
   {
      "hqstate" : "Maryland",
      "focus" : "General",
      "blendedsubjects" : "Core subjects, foreign language",
      "detail" : "Vision Academy",
      "hqcity" : "Baltimore",
      "gradesserved" : "K-12",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-innosight/connections-academy/",
      "postdate" : "May 16, 2011",
      "blendedgrades" : "9-10",
      "title" : "Connections Academy",
      "type" : "Nonprofit or for-profit service provider",
      "hq" : "Baltimore, Maryland",
      "blendedenrollment" : "43"
   },
   {
      "hqstate" : "Michigan",
      "focus" : "Urban",
      "blendedsubjects" : "Comprehensive",
      "detail" : " ",
      "hqcity" : "Detroit",
      "gradesserved" : "K-12",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-innosight/cornerstone-health-high-school/",
      "postdate" : "May 16, 2011",
      "blendedgrades" : "9-12",
      "title" : "Cornerstone Health High School",
      "type" : "CMO",
      "hq" : "Detroit, Michigan",
      "blendedenrollment" : "500"
   },
   {
      "hqstate" : "Minnesota",
      "focus" : "General, urban, gifted and talented, other",
      "blendedsubjects" : "Comprehensive, core subjects, electives, foreign language,math",
      "detail" : "Fusion, PASCAL, high school-to-college",
      "hqcity" : "St. Paul",
      "gradesserved" : "3-12",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-usersubmissions/cyber-village-academy/",
      "postdate" : "May 6, 2011",
      "blendedgrades" : "4-12",
      "title" : "Cyber Village Academy",
      "type" : "Individual charter school",
      "hq" : "St. Paul, Minnesota",
      "blendedenrollment" : "133"
   },
   {
      "hqstate" : "New Mexico",
      "focus" : "Dropout prevention/recovery",
      "blendedsubjects" : "Comprehensive, except some electives",
      "detail" : " ",
      "hqcity" : "Albuquerque",
      "gradesserved" : "PreK-12",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-innosight/ecademy/",
      "postdate" : "May 16, 2011",
      "blendedgrades" : "8-12",
      "title" : "eCADEMY",
      "type" : "District",
      "hq" : "Albuquerque, New Mexico",
      "blendedenrollment" : "1,500"
   },
   {
      "hqstate" : "New York",
      "focus" : "General",
      "blendedsubjects" : "Comprehensive",
      "detail" : "Dropout-solutions centers, blended products",
      "hqcity" : "New York City",
      "gradesserved" : "PreK-12",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-innosight/edisonlearning/",
      "postdate" : "May 16, 2011",
      "blendedgrades" : "9-12",
      "title" : "EdisonLearning",
      "type" : "Nonprofit or for-profit service provider",
      "hq" : "New York City, New York",
      "blendedenrollment" : "451,400 students across all products and service offerings"
   },
   {
      "hqstate" : "Nevada",
      "focus" : "General",
      "blendedsubjects" : "Comprehensive",
      "detail" : " Self-blend",
      "hqcity" : "Incline Village",
      "gradesserved" : "K-12, adult learners",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-usersubmissions/elearning-cafe-inc/",
      "postdate" : "February 9, 2012",
      "blendedgrades" : "K-12",
      "title" : "eLearning Café, Inc.",
      "type" : "Nonprofit or for-profit service provider",
      "hq" : "Incline Village, Nevada",
      "blendedenrollment" : "62"
   },
   {
      "hqstate" : "California",
      "focus" : "Gifted and talented",
      "blendedsubjects" : "Comprehensive",
      "detail" : " ",
      "hqcity" : "Stanford",
      "gradesserved" : "7-12",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-innosight/epgy-online-high-school/",
      "postdate" : "May 16, 2011",
      "blendedgrades" : "7-12",
      "title" : "EPGY Online High School",
      "type" : "Independent school",
      "hq" : "Stanford, California",
      "blendedenrollment" : "289"
   },
   {
      "hqstate" : "Utah",
      "focus" : "General, credit recovery",
      "blendedsubjects" : "Comprehensive",
      "hqcity" : "Provo",
      "gradesserved" : "K-12",
      "postdate" : "March 8, 2012",
      "blendedgrades" : "K-12",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-usersubmissions/eschool-provo/",
      "title" : "eSchool Provo",
      "type" : "District",
      "hq" : "Provo, Utah",
      "blendedenrollment" : "250"
   },
   {
      "hqstate" : "California",
      "focus" : "General",
      "blendedsubjects" : "16 courses",
      "detail" : " ",
      "hqcity" : "Anaheim",
      "gradesserved" : "K-12",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-innosight/fairmont-preparatory-academy/",
      "postdate" : "May 16, 2011",
      "blendedgrades" : "9-12",
      "title" : "Fairmont Preparatory Academy",
      "type" : "Independent school",
      "hq" : "Anaheim, California",
      "blendedenrollment" : "156"
   },
   {
      "hqstate" : "Colorado",
      "focus" : "Parochial",
      "blendedsubjects" : "Comprehensive",
      "detail" : "Faith Christian Online Learning Program",
      "hqcity" : "Arvada",
      "gradesserved" : "K-12",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-usersubmissions/faith-christian-academy/",
      "postdate" : "April 9, 2012",
      "blendedgrades" : "6-12",
      "title" : "Faith Christian Academy",
      "type" : "Independent school",
      "hq" : "Arvada, Colorado",
      "blendedenrollment" : "25"
   },
   {
      "hqstate" : "California",
      "focus" : "General",
      "blendedsubjects" : "Comprehensive",
      "detail" : "San Francisco Flex Academy, in partnership with K12, Inc.",
      "hqcity" : "San Francisco",
      "gradesserved" : "6-12",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-innosight/flex-public-schools/",
      "postdate" : "May 19, 2011",
      "blendedgrades" : "6-12",
      "title" : "Flex Public Schools",
      "type" : "CMO",
      "hq" : "San Francisco, California",
      "blendedenrollment" : "Target is 500 per school"
   },
   {
      "hqstate" : "Florida",
      "focus" : "General",
      "blendedsubjects" : "Comprehensive",
      "detail" : "Classic, ELearning Centers, Virtual Learning Labs, iPrep Academy (Miami-Dade)",
      "hqcity" : "Orlando",
      "gradesserved" : "K-12",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-innosight/florida-virtual-school-10/",
      "postdate" : "May 19, 2011",
      "blendedgrades" : "Classic: K-12 ELearning Centers and Virtual Learning Labs: 6-12 iPrep Academy: 11-12",
      "title" : "Florida Virtual School",
      "type" : "State virtual school",
      "hq" : "Orlando, Florida",
      "blendedenrollment" : "Classic: 83,956 (excludes home school; 2009-10 school year) ELearning Centers: 3,700 Virtual Learning Labs: 7,000 iPrep Academy 75-80 (2009-10 school year)"
   },
   {
      "hqstate" : "Michigan",
      "focus" : "Urban",
      "blendedsubjects" : "Core subjects",
      "detail" : "Centers of Innovation",
      "hqcity" : "Grand Rapids",
      "gradesserved" : "PreK-12",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-innosight/grand-rapids-public-schools/",
      "postdate" : "May 19, 2011",
      "blendedgrades" : "9-12 when fully operational",
      "title" : "Grand Rapids Public Schools",
      "type" : "District",
      "hq" : "Grand Rapids, Michigan",
      "blendedenrollment" : "Unavailable"
   },
   {
      "hqstate" : "Hawaii",
      "focus" : "General",
      "blendedsubjects" : "Comprehensive",
      "detail" : "In partnership with K12, Inc.",
      "hqcity" : "Ewa Beach",
      "gradesserved" : "K-12",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-innosight/hawaii-technology-academy/",
      "postdate" : "May 19, 2011",
      "blendedgrades" : "K-12",
      "title" : "Hawaii Technology Academy",
      "type" : "Individual charter school",
      "hq" : "Ewa Beach, Hawaii",
      "blendedenrollment" : "1,000"
   },
   {
      "hqstate" : "California",
      "focus" : "STEM",
      "blendedsubjects" : "Foreign language, math",
      "detail" : " ",
      "hqcity" : "San Diego",
      "gradesserved" : "K-12",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-innosight/high-tech-high-school/",
      "postdate" : "May 19, 2011",
      "blendedgrades" : "6-12",
      "title" : "High Tech High School",
      "type" : "CMO",
      "hq" : "San Diego, California",
      "blendedenrollment" : "4,128 students on ALEKS, 250 on Rosetta Stone"
   },
   {
      "hqstate" : "Indiana",
      "focus" : "General",
      "blendedsubjects" : "Comprehensive",
      "detail" : "In partnership with K12, Inc.",
      "hqcity" : "Indianapolis",
      "gradesserved" : "K-11",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-innosight/hoosier-academies/",
      "postdate" : "May 19, 2011",
      "blendedgrades" : "K-11",
      "title" : "Hoosier Academies",
      "type" : "Individual charter school",
      "hq" : "Indianapolis, Indiana",
      "blendedenrollment" : "528"
   },
   {
      "hqstate" : "Colorado",
      "focus" : "General",
      "blendedsubjects" : "Comprehensive",
      "detail" : "Supplemental, hybrid, online enhanced, online driver, credit recovery",
      "hqcity" : "Golden",
      "gradesserved" : "PreK-12",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-usersubmissions/jeffco-public-schools/",
      "postdate" : "May 6, 2011",
      "blendedgrades" : "7-12",
      "title" : "Jeffco Public Schools",
      "type" : "District",
      "hq" : "Golden, Colorado",
      "blendedenrollment" : "7,500"
   },
   {
      "hqstate" : "Nebraska",
      "focus" : "Parochial",
      "blendedsubjects" : "20 courses in catolog",
      "detail" : " ",
      "hqcity" : "Omaha",
      "gradesserved" : "9-12",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-innosight/jesuit-virtual-learning-academy/",
      "postdate" : "May 19, 2011",
      "blendedgrades" : "9-12",
      "title" : "Jesuit Virtual Learning Academy",
      "type" : "Nonprofit or for-profit service provider",
      "hq" : "Omaha, Nebraska",
      "blendedenrollment" : "81"
   },
   {
      "hqstate" : "Kentucky",
      "focus" : "General",
      "blendedsubjects" : "Kentucky Virtual High School: Comprehensive Pilot: Algebra I Hybrid grants: Varies",
      "detail" : "Kentucky Virtual High School, pilot, hybrid grants",
      "hqcity" : "Frankfort",
      "gradesserved" : "PreK-12",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-innosight/kentucky-department-of-education/",
      "postdate" : "May 26, 2011",
      "blendedgrades" : "Kentucky Virtual High School: 5-12 Pilot: Algebra I Hybrid grants: 9-12",
      "title" : "Kentucky Department of Education",
      "type" : "State department of education",
      "hq" : "Frankfort, Kentucky",
      "blendedenrollment" : "Kentucky Virtual High School: 700 Pilot: 8,000 Hybrid grants: ~900"
   },
   {
      "hqstate" : "California",
      "focus" : "Urban",
      "blendedsubjects" : "Core subjects",
      "detail" : "Empower Academy",
      "hqcity" : "Los Angeles",
      "gradesserved" : "K-8",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-innosight/kipp-la/",
      "postdate" : "May 26, 2011",
      "blendedgrades" : "K-4",
      "title" : "KIPP LA",
      "type" : "CMO",
      "hq" : "Los Angeles, California",
      "blendedenrollment" : "115"
   },
   {
      "hqstate" : "California",
      "focus" : "Urban",
      "blendedsubjects" : "Comprehensive",
      "detail" : " ",
      "hqcity" : "Oakland",
      "gradesserved" : "9-12",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-innosight/leadership-public-schools/",
      "postdate" : "May 26, 2011",
      "blendedgrades" : "9-12",
      "title" : "Leadership Public Schools",
      "type" : "CMO",
      "hq" : "Oakland, California",
      "blendedenrollment" : "1,500"
   },
   {
      "hqstate" : "California",
      "focus" : "General",
      "blendedsubjects" : "Math",
      "detail" : "Khan Academy Collaborative Partnership (Math)",
      "hqcity" : "Los Altos",
      "gradesserved" : "K-8",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/los-altos-school-district/",
      "postdate" : "February 28, 2012",
      "blendedgrades" : "5-8",
      "title" : "Los Altos School District",
      "type" : "District",
      "hq" : "Los Altos, California",
      "blendedenrollment" : "1,000+"
   },
   {
      "hqstate" : "Georgia",
      "focus" : "Rural",
      "blendedsubjects" : "Core subjects",
      "detail" : "Blended Learning @ Luella Middle School",
      "hqcity" : "McDonough",
      "gradesserved" : "PreK-12",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-usersubmissions/luella-middle-school/",
      "postdate" : "May 23, 2011",
      "blendedgrades" : "6-8",
      "title" : "Luella Middle School",
      "type" : "District",
      "hq" : "McDonough, Georgia",
      "blendedenrollment" : "857"
   },
   {
      "hqstate" : "Georgia",
      "focus" : "Turnaround",
      "blendedsubjects" : "Comprehensive",
      "hqcity" : "Atlanta",
      "gradesserved" : "K-12",
      "postdate" : "May 26, 2011",
      "blendedgrades" : "K-12",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-innosight/matchbook-learning-llc/",
      "title" : "Matchbook Learning, LLC",
      "type" : "Nonprofit or for-profit service provider",
      "hq" : "Atlanta, Georgia",
      "blendedenrollment" : "To be determined"
   },
   {
      "hqstate" : "Tennessee",
      "focus" : "General",
      "blendedsubjects" : "Comprehensive",
      "hqcity" : "Nashville",
      "gradesserved" : "PreK-12",
      "postdate" : "May 26, 2011",
      "blendedgrades" : "7-12",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-innosight/metropolitan-nashville-public-schools/",
      "title" : "Metropolitan Nashville Public Schools Virtual Learning",
      "type" : "District",
      "hq" : "Nashville, Tennessee",
      "blendedenrollment" : "~500"
   },
   {
      "hqstate" : "Michigan",
      "focus" : "General",
      "blendedsubjects" : "Comprehensive",
      "detail" : " ",
      "hqcity" : "Lansing",
      "gradesserved" : "6-12",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-innosight/michigan-virtual-school/",
      "postdate" : "May 26, 2011",
      "blendedgrades" : "6-12",
      "title" : "Michigan Virtual School",
      "type" : "Nonprofit or for-profit service provider",
      "hq" : "Lansing, Michigan",
      "blendedenrollment" : "15,000"
   },
   {
      "hqstate" : "California",
      "focus" : "General, urban, rural, dropout prevention/recovery, gifted and talented, STEM, turnaround, other",
      "blendedsubjects" : "STEM, math",
      "detail" : "Spatial Temporal (ST) Math instructional software",
      "hqcity" : "Santa Ana",
      "gradesserved" : "preK-5; 6-12",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-usersubmissions/mind-research-institute/",
      "postdate" : "February 13, 2012",
      "blendedgrades" : "PreK-5 and Secondary Intervention",
      "title" : "MIND Research Institute",
      "type" : "Nonprofit or for-profit service provider",
      "hq" : "Santa Ana, California",
      "blendedenrollment" : "350,000"
   },
   {
      "hqstate" : "Florida",
      "focus" : "General",
      "blendedsubjects" : "Comprehensive",
      "detail" : "Pasco eSchool",
      "hqcity" : "Land O’ Lakes",
      "gradesserved" : "PreK-12",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-usersubmissions/pasco-county-schools/",
      "postdate" : "May 23, 2011",
      "blendedgrades" : "4-12",
      "title" : "Pasco County Schools",
      "type" : "District",
      "hq" : "Land O’ Lakes, Florida",
      "blendedenrollment" : "~1,000"
   },
   {
      "hqstate" : "Arizona",
      "focus" : "General",
      "blendedsubjects" : "Comprehensive",
      "detail" : "Blended-learning centers",
      "hqcity" : "Chandler",
      "gradesserved" : "6-12",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-usersubmissions/primavera-online-high-school/",
      "postdate" : "July 27, 2011",
      "blendedgrades" : "9-12",
      "title" : "Primavera Online High School",
      "type" : "CMO",
      "hq" : "Chandler, Arizona",
      "blendedenrollment" : "Too early to determine"
   },
   {
      "hqstate" : "Pennsylvania",
      "focus" : "General",
      "blendedsubjects" : "Comprehensive",
      "detail" : "Infinity Cyber Academy",
      "hqcity" : "Quakertown",
      "gradesserved" : "K-12",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-usersubmissions/quakertown-community-school-district-2/",
      "postdate" : "March 28, 2012",
      "blendedgrades" : "6-12",
      "title" : "Quakertown Community School District",
      "type" : "District",
      "hq" : "Quakertown, Pennsylvania",
      "blendedenrollment" : "514"
   },
   {
      "hqstate" : "New York",
      "focus" : "Urban",
      "blendedsubjects" : "Comprehensive",
      "detail" : "",
      "hqcity" : "New York",
      "gradesserved" : "PreK-12",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-innosight/quest-to-learn/",
      "postdate" : "May 26, 2011",
      "blendedgrades" : "6-12",
      "title" : "Quest to Learn",
      "type" : "District",
      "hq" : "New York, New York",
      "blendedenrollment" : "140 (grades 6 and 7 only)"
   },
   {
      "hqstate" : "California",
      "focus" : "General",
      "blendedsubjects" : "Comprehensive",
      "detail" : " ",
      "hqcity" : "Riverside",
      "gradesserved" : "PreK-12",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-innosight/riverside-virtual-school/",
      "postdate" : "May 26, 2011",
      "blendedgrades" : "6-12",
      "title" : "Riverside Virtual School",
      "type" : "District",
      "hq" : "Riverside, California",
      "blendedenrollment" : "3,661 course enrollments (2009-10 school year)"
   },
   {
      "hqstate" : "California",
      "focus" : "Urban",
      "blendedsubjects" : "Core subjects",
      "detail" : " ",
      "hqcity" : "San Jose",
      "gradesserved" : "K-5",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-innosight/rocketship-education/",
      "postdate" : "May 26, 2011",
      "blendedgrades" : "K-5",
      "title" : "Rocketship Education",
      "type" : "CMO",
      "hq" : "San Jose, California",
      "blendedenrollment" : "1,328"
   },
   {
      "hqstate" : "California",
      "focus" : "Dropout prevention/recovery",
      "blendedsubjects" : "Core subjects",
      "detail" : " ",
      "hqcity" : "Oceanside",
      "gradesserved" : "Ages 16-24",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-innosight/school-for-integrated-academics-and-technologies-siatech/",
      "postdate" : "May 26, 2011",
      "blendedgrades" : "9-12",
      "title" : "School for Integrated Academics and Technologies (SIATech)",
      "type" : "CMO",
      "hq" : "Oceanside, California",
      "blendedenrollment" : "4,500 to 4,800 (2009-10 school year)"
   },
   {
      "hqstate" : "New York",
      "focus" : "Urban",
      "blendedsubjects" : "Math",
      "detail" : " ",
      "hqcity" : "New York",
      "gradesserved" : "PreK-12",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-innosight/school-of-one/",
      "postdate" : "July 21, 2011",
      "blendedgrades" : "6-8",
      "title" : "School of One",
      "type" : "District",
      "hq" : "New York, New York",
      "blendedenrollment" : "1,477"
   },
   {
      "hqstate" : "California",
      "focus" : "General",
      "blendedsubjects" : "Core subjects",
      "detail" : "Sixth period, learning center",
      "hqcity" : "Arcata",
      "gradesserved" : "9-12",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-innosight/six-rivers-charter-high-school/",
      "postdate" : "July 21, 2011",
      "blendedgrades" : "9-12",
      "title" : "Six Rivers Charter High School",
      "type" : "Individual charter school",
      "hq" : "Arcata, California",
      "blendedenrollment" : "6th period: 15 Learning center: 35"
   },
   {
      "hqstate" : "California",
      "focus" : "Gifted and talented",
      "blendedsubjects" : "Math",
      "hqcity" : "Culver City",
      "gradesserved" : "6-12",
      "postdate" : "March 23, 2012",
      "blendedgrades" : "6-12",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-usersubmissions/star-prep-academy/",
      "title" : "STAR Prep Academy",
      "type" : "Independent school",
      "hq" : "Culver City, California",
      "blendedenrollment" : "40"
   },
   {
      "hqstate" : "Minnesota",
      "focus" : "General",
      "blendedsubjects" : "Math",
      "hqcity" : "Stillwater",
      "gradesserved" : "PreK-12",
      "postdate" : "April 19, 2012",
      "blendedgrades" : "4-6",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-innosight/stillwater-area-public-schools/",
      "title" : "Stillwater Area Public Schools",
      "type" : "District",
      "hq" : "Stillwater, Minnesota",
      "blendedenrollment" : "650"
   },
   {
      "hqstate" : "California",
      "focus" : "Urban",
      "blendedsubjects" : "Comprehensive",
      "detail" : " ",
      "hqcity" : "Los Angeles",
      "gradesserved" : "9-12",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-innosight/usc-hybrid-high-school/",
      "postdate" : "July 21, 2011",
      "blendedgrades" : "9-12",
      "title" : "USC Hybrid High School",
      "type" : "Individual charter school",
      "hq" : "Los Angeles, California",
      "blendedenrollment" : "600 when fully operational"
   },
   {
      "hqstate" : "Illinois",
      "focus" : "Urban",
      "blendedsubjects" : "Comprehensive",
      "detail" : " ",
      "hqcity" : "Chicago",
      "gradesserved" : "9-12",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-innosight/voise-academy-high-school/",
      "postdate" : "July 21, 2011",
      "blendedgrades" : "9-12",
      "title" : "VOISE Academy High School",
      "type" : "District",
      "hq" : "Chicago, Illinois",
      "blendedenrollment" : "550"
   },
   {
      "hqstate" : "Ohio",
      "focus" : "Dropout prevention/recovery",
      "blendedsubjects" : "Comprehensive",
      "detail" : "LifeSkills Centers",
      "hqcity" : "Akron",
      "gradesserved" : "Ages 16-21",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-innosight/white-hat-management/",
      "postdate" : "July 21, 2011",
      "blendedgrades" : "Ages 16-21",
      "title" : "White Hat Management",
      "type" : "Nonprofit or for-profit service provider",
      "hq" : "Akron, Ohio",
      "blendedenrollment" : "8,000"
   },
   {
      "hqstate" : "Kansas",
      "focus" : "Urban",
      "blendedsubjects" : "Core subjects",
      "detail" : "Learning Centers",
      "hqcity" : "Wichita",
      "gradesserved" : "PreK-12",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-innosight/wichita-public-schools/",
      "postdate" : "July 21, 2011",
      "blendedgrades" : "10-12",
      "title" : "Wichita Public Schools",
      "type" : "District",
      "hq" : "Wichita, Kansas",
      "blendedenrollment" : "1.361"
   },
   {
      "hqstate" : "Illinois",
      "focus" : "Credit recovery, dropout prevention/recovery",
      "blendedsubjects" : "Comprehensive",
      "hqcity" : "Chicago",
      "gradesserved" : "11-12",
      "postdate" : "March 7, 2012",
      "blendedgrades" : "11-12",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-innosight/youth-connection-charter-school-virtual-high-school/",
      "title" : "Youth Connection Charter School Virtual High School",
      "type" : "Individual charter school",
      "hq" : "Chicago, Illinois",
      "blendedenrollment" : "164"
   }
]
