table_data = [
   {
      "hqstate" : "Alabama",
      "programmodels" : "Online Lab, Self-Blend",
      "focus" : "Rural",
      "blendedsubjects" : "Comprehensive",
      "hqcity" : "Montgomery",
      "gradesserved" : "8-12",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-innosight/access-distance-learning-5/",
      "postdate" : "May 12, 2011",
      "blendedgrades" : "8-12",
      "title" : "ACCESS Distance Learning",
      "type" : "State department of education",
      "hq" : "Montgomery, Alabama",
      "blendedenrollment" : "41,161 (2009-10 school year)"
   },
   {
      "hqstate" : "Texas",
      "programmodels" : "Flex",
      "focus" : "General",
      "blendedsubjects" : "Foreign language, math, reading, other",
      "detail" : " ",
      "hqcity" : "Austin",
      "gradesserved" : "1-5",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-innosight/acton-academy/",
      "postdate" : "May 12, 2011",
      "blendedgrades" : "1-5",
      "title" : "Acton Academy",
      "type" : "Independent school",
      "hq" : "Austin, Texas",
      "blendedenrollment" : "16"
   },
   {
      "hqstate" : "Virginia",
      "programmodels" : "Flex",
      "focus" : "Dropout prevention/recovery",
      "blendedsubjects" : "Comprehensive",
      "detail" : " ",
      "hqcity" : "Williamsburg",
      "gradesserved" : "9-12",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-innosight/advancepath-academics-inc/",
      "postdate" : "May 12, 2011",
      "blendedgrades" : "9-12",
      "title" : "AdvancePath Academics, Inc.",
      "type" : "Nonprofit or for-profit service provider",
      "hq" : "Williamsburg, Virginia",
      "blendedenrollment" : "4,000-4,5000 in 23 academies"
   },
   {
      "hqstate" : "California",
      "programmodels" : "Rotation, Online Driver",
      "focus" : "Urban",
      "blendedsubjects" : "Core subjects",
      "detail" : "Pilot study, summer program",
      "hqcity" : "Los Angeles",
      "gradesserved" : "9-12",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-innosight/alliance-college-ready-public-schools/",
      "postdate" : "May 12, 2011",
      "blendedgrades" : "Pilot study: 9 Summer program: 9-12",
      "title" : "Alliance College-Ready Public Schools",
      "type" : "CMO",
      "hq" : "Los Angeles, California",
      "blendedenrollment" : "Unavailable"
   },
   {
      "hqstate" : "Rhode Island",
      "programmodels" : "Face-to-Face Driver",
      "focus" : "Urban",
      "detail" : " ",
      "hqcity" : "Providence",
      "gradesserved" : "9-12",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-innosight/big-picture-learning/",
      "postdate" : "May 12, 2011",
      "blendedgrades" : "9-12",
      "title" : "Big Picture Learning",
      "type" : "Nonprofit or for-profit service provider",
      "hq" : "Providence, Rhode Island",
      "blendedenrollment" : "9,000"
   },
   {
      "hqstate" : "New York",
      "programmodels" : "Rotation",
      "focus" : "Urban",
      "blendedsubjects" : "Core subjects",
      "detail" : "In partnership with Diploma Plus",
      "hqcity" : "New York",
      "gradesserved" : "PreK-12",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-innosight/brownsville-academy-high-school/",
      "postdate" : "May 13, 2011",
      "blendedgrades" : "9-12",
      "title" : "Brownsville Academy High School",
      "type" : "District",
      "hq" : "New York, New York",
      "blendedenrollment" : "171"
   },
   {
      "hqstate" : "Pennsylvania",
      "programmodels" : "Online Lab, Self-Blend",
      "focus" : "General",
      "blendedsubjects" : "Comprehensive",
      "detail" : " ",
      "hqcity" : "Enola",
      "gradesserved" : "K-12",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-innosight/capital-area-online-learning-association/",
      "postdate" : "May 13, 2011",
      "blendedgrades" : "6-12",
      "title" : "Capital Area Online Learning Association",
      "type" : "State intermediate unit",
      "hq" : "Enola, Pennsylvania",
      "blendedenrollment" : "1,224"
   },
   {
      "hqstate" : "Arizona",
      "programmodels" : "Rotation",
      "focus" : "Urban",
      "blendedsubjects" : "Comprehensive",
      "detail" : " ",
      "hqcity" : "Yuma",
      "gradesserved" : "6-12",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-innosight/carpe-diem-collegiate-high-school-and-middle-school-cdchs/",
      "postdate" : "May 13, 2011",
      "blendedgrades" : "6-12",
      "title" : "Carpe Diem Collegiate High School and Middle School (CDCHS)",
      "type" : "CMO",
      "hq" : "Yuma, Arizona",
      "blendedenrollment" : "273"
   },
   {
      "hqstate" : "Illinois",
      "programmodels" : "Face-to-Face Driver",
      "focus" : "Urban",
      "blendedsubjects" : "Core subjects",
      "detail" : " ",
      "hqcity" : "Chicago",
      "gradesserved" : "K-12",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-innosight/chicago-international-charter-school/",
      "postdate" : "May 13, 2011",
      "blendedgrades" : "6-12",
      "title" : "Chicago International Charter School",
      "type" : "CMO",
      "hq" : "Chicago, Illinois",
      "blendedenrollment" : "To be determined"
   },
   {
      "hqstate" : "Illinois",
      "programmodels" : "Rotation",
      "focus" : "Urban",
      "blendedsubjects" : "Math, reading",
      "detail" : "Additional Learning Opportunities Initiative",
      "hqcity" : "Chicago",
      "gradesserved" : "PreK-12",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-innosight/chicago-public-schools/",
      "postdate" : "May 13, 2011",
      "blendedgrades" : "1-8",
      "title" : "Chicago Public Schools",
      "type" : "District",
      "hq" : "Chicago, Illinois",
      "blendedenrollment" : "6,000 (in first 15-school pilot)"
   },
   {
      "hqstate" : "New York",
      "programmodels" : "Rotation",
      "focus" : "Urban",
      "blendedsubjects" : "Comprehensive",
      "detail" : " ",
      "hqcity" : "New York",
      "gradesserved" : "9-12",
      "url" : "http://www.innosightinstitute.org/blended-learning-2/blprofiles-innosight/city-prep-academies/",
      "postdate" : "May 13, 2011",
      "blendedgrades" : "9-12",
      "title" : "City Prep Academies",
      "type" : "CMO",
      "hq" : "New York, New York",
      "blendedenrollment" : "To be determined"
   }
]
